emc-isilon/pike

pike/model.py, pike/test.py, test/negotiate.py
New test cases are passing
head-11833-1# PIKE_SERVER="::1" PIKE_CREDS="ISI\\blah%1234" PIKE_SHARE="ifs" unit2 discover -s . -p negotiate.py -v
test_downlevel (negotiate.CapMultichannel) ... ok
test_downlevel_no_advert (negotiate.CapMultichannel) ... ok
test_smb3 (negotiate.CapMultichannel) ... ok
test_smb3_many_capabilities (negotiate.CapMultichannel) ... ok
test_smb3_no_advert (negotiate.CapMultichannel) ... ok
test_downlevel (negotiate.CapMulticredit) ... ok
test_smb21 (negotiate.CapMulticredit) ... ok
test_smb3 (negotiate.CapMulticredit) ... ok
test_smb3_many_capabilities (negotiate.CapMulticredit) ... ok
test_downlevel (negotiate.CapPersistent) ... ok
test_downlevel_no_advert (negotiate.CapPersistent) ... ok
test_smb3 (negotiate.CapPersistent) ... ok
test_smb3_many_capabilities …
=> Calsoft refresh from Pike_Deliverable_18Mar.tar.gz

pike/transport.py, setup.py
Pulling in this trivial fix for an incorrectly named variable
=> hotfix for incorrect variable name

pike/auth.py, pike/model.py, pike/ntlm.py, pike/test/internal/test_callbacks.py, setup.py
This change brings in a new callback system for extended testing and abstracts the authentication providers a bit more.
This change is required for generating accounting logs.
=> Integrate version 0.2.2

pike/transport.py, setup.py
=> Hotfix 0.2.5.1

pike/__init__.py, pike/model.py, pike/nttime.py, pike/smb2.py, pike/transport.py
Various improvements that came out of rmartorell's encryption testing.
=> Integrate 0.2.7

pike/__init__.py, pike/model.py, pike/test/credit.py
Fixes credit accounting and adds credit test cases
=> Integrate 0.2.10

pike/__init__.py, pike/test/credit.py
bump version to 0.2.11
fixes #35 too
=> credit test: allow for arbitrary number of starting credits

pike/test/invalid_session.py, pike/test/invalid_tree.py
Add new tests exercising scenarios where requests have invalid
session or tree id set.
=> Add new tests

pike/__init__.py, pike/smb2.py
FSCTL_SET_SPARSE
FSCTL_SET_ZERO_DATA
author: mfurer
contributor: jjose
=> add FSCTL codes:

pike/model.py, pike/smb2.py, pike/test/copychunk.py
add resume key and copychunk_write tests
please help review and comment
=> add resume key and copychunk_write tests

pike/__init__.py, pike/model.py, pike/smb2.py
Changes to enumerate snapshots and pulled in sparse and zeroize requests from individual test cases.
=> Added pike functions for enum snapshots & sparse

pike/model.py
=> pike.model: Channel.echo returns the response

pike/__init__.py, pike/test/__init__.py, pike/test/ioctl.py
Test results attached:
[Results_0_2_x.txt](https://github.com/emc-isilon/pike/files/4692558/Results_0_2_x.txt)
=> Set required client min & max dialect before test

pike/model.py, pike/ntstatus.py, pike/test/readwrite.py
Fixes https://github.com/emc-isilon/pike/issues/85
=> ISILONQE-976 : pike.ntstatus.pike_status to handle expected error

pike/model.py, pike/test/__init__.py, pike/test/internal/test_client.py, pike/test/ioctl.py
Refer comments in https://github.com/emc-isilon/pike/pull/80.
Testing:
[TestResults.txt](https://github.com/emc-isilon/pike/files/4801340/TestResults.txt)
=> Br isilonqe 977

.github/workflows/test_samba.yml
Run tests for push and pull_request
=> .github/workflows/test_samba.yml: build on pull_request

README.md
Note pip install command.
Note pypi.org link.
Consistent use of command prompt vs. code.
Wording tweaks, newline tweaks.
=> README.md add pip install command, fixups

.github/workflows/test_samba.yml
don't let changes to the upstream break CI testing
=> test_samba.yml: pin dperson/samba container hash

README.md, build_all_wheels.sh, pike/auth.py, pike/model.py, pykerb/kerberos.c, setup.py
Minimal Testing Done till now: On Python 3.6
Build: python setup.py bdist_wheel
Created a minimal krb5.conf
Export user as `user_1` and pass as default one.
echo " ip       fqdn" >> /etc/hosts
printf "%b" "addent -password -p $user -k 1 -e rc4-hmac\n$pass\nwrite_kt /home/keytabs/$user/username.keytab" | ktutil
kinit -kt /home/keytabs/user_1/username.keytab user_1
PIKE_SERVER=fqdn python -c 'from pike.test import TreeConnect; tc = TreeConnect(share="ifs")()'
ip -> IP address of the server
fqdn -> hostname after domain join.
Network trace verified to do kerberos auth.
In addition to uplift this PR also has changes to do a wheel build from PR https://github.com/emc-isilon/pike/pull/113
cc: @isi-rszczesniak
=> Uplift kerberos changes

build_all_wheels.sh, pykerb/kerberos.c
* `PY_SSIZE_T_CLEAN`
* py2/py3 compat `#ifs`
* update `build_all_wheels.sh` to install `build[virtualenv]` and then use _that_ to create the virtualenv for the sdist and wheel
=> pykerb support for py2.7 and py3.10

pike/model.py
fixes #121 buffer_length not properly propagated in change_notify function
=> carry buffer_length argument in Channel.change_notify

pike/model.py, pike/smb2.py
* Implement `input_buffer` support for `QueryInfoRequest`
* add `QueryQuotaInfo` structure found in `SMB2_0_INFO_QUOTA` request
* add `FileQuotaInformation` structure found in `SMB2_0_INFO_QUOTA` response
* add helper methods to `pike.model.Channel` for `query_quota_info`
=> Implement Quota query info type

pike/__init__.py, pike/model.py, pike/test/__init__.py, setup.py
---Added retry in connect call to deal with sudden network issues
=> Changes in connect function

src/pike/smb2.py
Added decoding support for FSCTL_QUERY_NETWORK_INTERFACE_INFO
=> Added decoding support for FSCTL_QUERY_NETWORK_INTERFACE_INFO

tests/test_basic_io.py
---A basic smb2 test to do
session setup
tree connect
file create, write, read, close
cc: @sudosantanu @marchhare09
=> Added test_basic_io.py

buildwheel/Dockerfile, pyproject.toml
CI run works fine.
cc: @sudosantanu @marchhare09
=> Fixed yum repo in CI

buildwheel/Dockerfile, pyproject.toml
Reverts emc-isilon/pike#139
Some more fix is needed.
=> Revert "Fixed yum repo in CI"

pike/test/persistent.py
---Increased timeout so that test is more resilient to slowness in virtual environment.
Changes picked from https://github.com/emc-isilon/pike/pull/134 for py2 branch.
=> Improved persistent.py

pike/__init__.py
=> Updated pike version to 0.2.30
