emc-isilon/pike

pike/model.py
pike/smb2.py
test/queryondiskid.py

head-11833-1# PIKE_SERVER="localhost" PIKE_CREDS="ISI\\blah%1234" PIKE_SHARE="ifs" unit2 discover -s . -p queryondiskid.py -v
test_qfid_diff_file (queryondiskid.TestQueryOnDiskID) ... ok
test_qfid_functional (queryondiskid.TestQueryOnDiskID) ... ok
test_qfid_same_file (queryondiskid.TestQueryOnDiskID) ... ok
test_qfid_same_file_seq (queryondiskid.TestQueryOnDiskID) ... ok
test_qfid_same_file_seq_delete (queryondiskid.TestQueryOnDiskID) ... ok
----------------------------------------------------------------------
Ran 5 tests in 2.117s
OK

Add Query On Disk ID support

---

pike/model.py
pike/smb2.py
pike/test.py
test/copychunk.py

Windows Server 2012r2:
head-11858-1# PYTHONPATH=test unit2 -v copychunk
test_copy_big_file (copychunk.TestServerSideCopy) ... ok
test_copy_max_chunks (copychunk.TestServerSideCopy) ... ok
test_copy_multiple_chunks (copychunk.TestServerSideCopy) ... ok
test_copy_small_file (copychunk.TestServerSideCopy) ... ok
test_neg_dst_exc_brl (copychunk.TestServerSideCopy) ... ok
test_neg_dst_is_a_dir (copychunk.TestServerSideCopy) ... ok
test_neg_dst_no_read (copychunk.TestServerSideCopy) ... ok
test_neg_dst_no_write (copychunk.TestServerSideCopy) ... ok
test_neg_src_exc_brl (copychunk.TestServerSideCopy) ... ok
test_neg_src_no_read (copychunk.TestServerSideCopy) ... ok
test_offset_copy_big_file (copychunk.TestServerSideCopy) ... ok
test_offset_copy_multiple_chunks (copychunk.TestServerSideCopy) ... …

Add copychunk support and test cases

---

pike/model.py
pike/smb2.py
test/reparse.py

Windows Server 2008r2
head-11858-1# PYTHONPATH=test unit2 -v reparse
test_set_get_reparse_point (reparse.TestReparsePoint) ... ok
test_symbolic_link_error_response (reparse.TestReparsePoint) ... ok
----------------------------------------------------------------------
Ran 2 tests in 1.505s
OK
OneFS 8.0
head-11858-1# PYTHONPATH=test unit2 -v reparse
test_set_get_reparse_point (reparse.TestReparsePoint) ... ok
test_symbolic_link_error_response (reparse.TestReparsePoint) ... ok
----------------------------------------------------------------------
Ran 2 tests in 0.891s
OK

proper smb2 reparse point and symlink support

---

pike/smb2.py

If the signature field of a smb2 packet is already set, then use that directly. Otherwise calculate the signature.

allow inserting custom signature field in smb2 header

---

pike/test/__init__.py
setup.py

This change adds a suite generator to pike.test so that all tests can be easily run without invoking discover:
```python -m unittest pike.test.suite```
The PikeTestSuite is used to create the suite in order to easily allow downstream forks to customize the test list generated. The example implementation skips test cases based on test method name.

Integrate 0.2.3

---

pike/model.py
pike/netbios.py
pike/nttime.py
pike/smb2.py
pike/test/negotiate.py
setup.py

* Add timewarp/enumerate snapshot support
Minor fixes:
* netbios frame `len` field can now be modified by the test
* negotiate.py uses the default client (for accounting purposes)
Will be merging 11/28, please send feedback by then.

Integrate version 0.2.4

---

pike/core.py
pike/crypto.py
pike/model.py
pike/smb2.py
pike/transport.py
setup.py

This version vastly improves transport-level error handling on linux.
Also generalize the query info system to allow querying info types which do not have structures and decoders predefined. Also allows for calling set info with an arbitrary buffer.
This change will be merged on or after 12/12. Please submit feedback by then.

Integrate Version 0.2.5

---

pike/MakeKitBuild
pike/__init__.py
pike/auth.py
pike/model.py
pike/smb2.py
pike/test/__init__.py
pike/test/ioctl.py
setup.py

Fixes:
-------
* calculate proper sequence number for multicredit requests (b78bc5b)
* fix QueryInfoResponse file info class marshalling
* ValidateNegotiateInfo test only applies to dialects 3.0.0 and 3.0.2
Enhancements:
---------
* PIKE_CREDS can now be specified without a fake domain: "test_user%testpasswd" is now acceptable
* Pike client/connection callback functionality can be used with a context manager
* Pike version is now shipped with the package and can be queried from code

Integrate 0.2.6

---

pike/__init__.py
pike/model.py
pike/smb2.py

Pulls in rodolfo's latest changes required for testing the encryption branch.
Save a few more reserved fields and separate flush helper function into 2 parts.

integrate 0.2.8

---

pike/__init__.py
pike/model.py
pike/smb2.py
pike/test/compound.py

* fixes issue where blindly decoding the "extra" byte as specified in [MS-SMB2] 2.2.2 results in BufferOverrun
* add property `dialect_revision` to `Connection` class
* add additional test cases to pike.test.compound

Fix ErrorResponse handling [0.2.16]

---

pike/ntlm.py

PyCryptodome DES.new constructor requires explicit mode declaration.
This code was previously using PyCrypto, which defaulted to MODE_ECB, so
we use that here.
Additionally importing the name as DES resulted in the function defined
as DES overriding the import. That was broken here:
https://github.com/emc-isilon/pike/commit/7eec789779e7260b5f3921912f0c1afbe3203113#diff-eac4830f11f78da64d1e83582502fbc9

Fix NTLMv1 authentication

---

pike/model.py
pike/test/copychunk.py

fixes some interoperability issues with OneFS (also my editor automatically fixes trailing whitespace)
test results:
Windows 2016
```
root@337619c88bb4:/git/pike# PIKE_SERVER=mfsea-w16-01 PIKE_SHARE=ifs PIKE_CREDS=administrator%a python -m unittest -v pike.test.copychunk.TestServerSideCopy
test_bogus_resume_key (pike.test.copychunk.TestServerSideCopy) ... ok
test_copy_big_file (pike.test.copychunk.TestServerSideCopy) ... ok
test_copy_max_chunks (pike.test.copychunk.TestServerSideCopy) ... ok
test_copy_multiple_chunks (pike.test.copychunk.TestServerSideCopy) ... ok
test_copy_small_file (pike.test.copychunk.TestServerSideCopy) ... ok
test_copy_write_max_chunks (pike.test.copychunk.TestServerSideCopy) ... ok
test_copy_write_multiple_chunks (pike.test.copychunk.TestServerSideCopy) ... ok …
```

Minor fixes to new copychunk tests

---

pike/test/compound.py
pike/test/querydirectory.py

C:\Python27\Lib\site-packages\pike\test>python -m unittest -v compound.CompoundTest
test_create_close (compound.CompoundTest) ...
ok
test_create_faied_and_query (compound.CompoundTest) ...
ok
test_create_query_close (compound.CompoundTest) ...
ok
test_create_write_close (compound.CompoundTest) ...
ok
test_create_write_close_access_denied (compound.CompoundTest) ...
ok
----------------------------------------------------------------------
Ran 5 tests in 8.856s
OK
C:\Python27\Lib\site-packages\pike\test>python -m unittest -v querydirectory.QueryDirectoryTest
test_file_directory_info (querydirectory.QueryDirectoryTest) ...
ok
test_file_id_both_directory_information (querydirectory.QueryDirectoryTest) ...
ok
test_restart_scan (querydirectory.QueryDirectoryTest) ...
ok
test_specific_name …

Pike code coverage

---

pike/__init__.py
pike/model.py

Previously, passing an object that isn't a `Netbios` frame to `submit` or `transceive` will cause the pike internal loop to hang -- additionally no `Future` is allocated so the 30-second default timeout does not apply.
This change allows pike to fail fast when an inappropriate object is supplied. This is mainly for the benefit of the programmer during test development.

Raise RequestError when attempting to submit non-Netbios frames 

---

pike/model.py
pike/smb2.py
pike/test/durable.py
pike/test/persistent.py

@AnnieL01 I took your latest commits from yesterday and packaged them up like this. I think this is ready to merge, but please give it another once over and confirm that it meets your expectations.
PIKE_SERVER=mfsea-w16-01 PIKE_SHARE=ifs PIKE_CREDS=administrator%password python -m unittest -v pike.test.durable
test_durable (pike.test.durable.DurableHandleTest) ... ok
test_durable_invalidate (pike.test.durable.DurableHandleTest) ... ok
test_durable_reconnect (pike.test.durable.DurableHandleTest) ... ok
test_durable_reconnect_fails_client_guid (pike.test.durable.DurableHandleTest) ... ok
test_durable_reconnect_v2 (pike.test.durable.DurableHandleTest) ... ok
test_durable_reconnect_v2_fails_client_guid (pike.test.durable.DurableHandleTest) ... ok
test_durable_v2 …

Network Resiliency Request (Resilient Handles) tests

---

pike/model.py

this causes exceptions to be raised during the completion routine

pike/model.py: network resiliency callback: use resp_future.result()

---

pike/__init__.py
pike/model.py
pike/test/lease.py

* if callback is not callable raise `CallbackError`
* don't dispose the handle in `close_submit` (do it after the close returns!)
* pass `completion_filter` to struct in `change_notify_request`
* get rid of `__init__` function in pike/test/lease.py (needed for pytest compatability)

[Helix 3] Fix minor bugs and longstanding annoyances

---

pike/__init__.py
pike/test/__init__.py

this ends pike support for python 2.6

remove unittest2

---

pike/model.py
pike/netbios.py
pike/test/compound.py
pike/test/copychunk.py

`pike.netbios.Netbios.adopt` will re-parent a frame under the current netbios frame, making a chain of Smb2 requests
`pike.model.RelatedOpen` can be used where the API expects an `Open` to indicate that the operation should use a handle from a previous chained Create

Make compound request helpers part of official API

---

pike/smb2.py
pike/test/__init__.py
setup.py

While pike doesn't directly depend on `pytest`, these changes make pike easier to use outside the context of a unittest `TestCase` subclass.
Extract `TreeConnect` mechanism from `pike.test.PikeTest` (subclass of `unittest.TestCase`) into its own standalone class which can be used comfortably without unittest.
The new `TreeConnect` extends the old `PikeTest.tree_connect` function to allow more customization and better control over the process of establishing the connection, authenticating, and performing the tree connect. Each of these phases is exposed as a separate helper function to decouple the sequence of operations.
The `TreeConnect` instance can be used as a context manager to automatically clean up. Additionally, `close` and `__call__` methods are provided to allow for easily …

Generalize pike test infrastructure

---

pike/core.py
pike/crypto.py
pike/model.py
pike/netbios.py
pike/smb2.py

Create a `_log_str` interface in core.Frame which can be overridden to provide a string used for logging.
Define some `_log_str` overrides to provide context for common SMB2 operations such as Create, Read, Write, Query/Set Info, QueryDirectory, TreeConnect, and Negotiate
Before: https://gist.github.com/isi-mfurer/cb764230afea1289e7220b1906bd9025
After: https://gist.github.com/isi-mfurer/c1a07f3a88a7d538ebf10dd0c55b89e2

Improve per-operation DEBUG logging

---

pike/core.py

`BufferOverrun` is inactionable unless it includes enough information to determine why the error occured.
Example output
```
File "/Users/mfurer/code/isilon/pike/pike/core.py", line 534, in parse
self.decode(cursor)
File "/Users/mfurer/code/isilon/pike/pike/core.py", line 523, in decode
self._decode(cur)
File "/Users/mfurer/code/isilon/pike/pike/netbios.py", line 72, in _decode
with cur.bounded(cur, end):
File "/Users/mfurer/code/isilon/pike/pike/core.py", line 371, in bounded
self._check_bounds(lower, upper)
File "/Users/mfurer/code/isilon/pike/pike/core.py", line 279, in _check_bounds
raise BufferOverrun(self, end, upper)
pike.core.BufferOverrun: 280 is above upper bound 278 in Cursor(<array.array object at 0x10ca37d70>,4,(None, None))
Packet buffer: …
```

BufferOverrun will include full packet bytes

---

pike/smb2.py
pike/test/changenotify.py

[internal PSCALE-13621]
Avoid triggering ErrorResponse handling for STATUS_NOTIFY_CLEANUP. According to the specification, a Notify response with this status is not an error.
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/f2b4183a-29c2-4fc0-a5de-fe290408f68c
https://github.com/isi-mfurer/pike/runs/762860965
(look for `test_change_notify_cancel`)

pike.smb2: ChangeNotifyResponse allows STATUS_NOTIFY_CLEANUP

---

.github/workflows/test_samba.yml
pike/__init__.py
pike/auth.py
pike/core.py
pike/crypto.py
pike/digest.py
pike/model.py
pike/netbios.py
pike/ntlm.py
pike/smb2.py
pike/test/compound.py
pike/test/copychunk.py
pike/test/credit.py
pike/test/multichannel.py

Pave the way for py3.9 compatibility
Internal test suite is passing against 3.9-dev and 3.10-dev 🎉 
https://github.com/isi-mfurer/pike/actions/runs/129171310

replace deprecated array.array.tostring usage with tobytes

---

pike/test/__init__.py

Recent versions of samba appear to have disfavor CCM by default so this test always returns GCM encryption, even when it's not preferred.

CI skip test_encryption_capabilities_both_prefer_ccm

---

pike/pytest_support.py
pike/test/__init__.py
setup.py

Expose `require_dialect`, `require_capabilities`, and `require_share_capabilities` as pytest marks.
Expose `pike_TreeConnect` fixture as entry point for establishing a pike session without a base class.
Apply require marks inside `pike_TreeConnect` fixture.

Add pytest plugin pike.conftest

---

.github/workflows/test_samba.yml
pike/core.py
pike/model.py

Add context to `TimeoutError` by optionally allowing it to be raised `with_future` specified. If the `Future` has a `.request` attribute, then it will be included in the `TimeoutError` string representation.
Callers may catch the `TimeoutError` and further inspect the `.future` or even wait for it again.
Update pike's use of `Future` to include relevant "request" context information where possible.
Existing raisers of `pike.model.TimeoutError` outside of this package are unaffected as the signature and behavior of TimeoutError are backward compatible with the previous implementation.
No explicit test cases are added for this change. Some scenarios were manually generated as an example and to check all code paths.
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module> …
```

[ISILONQE-1417] Pike TimeoutError should be actionable

---

.github/workflows/test_samba.yml
pike/model.py
pike/smb2.py
setup.py

* `pike.smb2.QueryInfoResponse` can now correctly read multiple items from the buffer
* `pike.model.Channel.query_file_info` behavior change is pending
* Future releases will return the `QueryInfoResponse` itself instead of the first child of the response

QueryInfoResponse can contain multiple children

---

setup.py

really this should have slid in with #88
discovering the problem now attempting to add pike as a dependency in poetry, which actually cares about satisfying requirements

setup.py: do not set an upper bound on python version

---

README.md
setup.py

Different frameworks read different classifier field values (i.e. pypi, github, pip, etc.). So fill in a few more of them.
Also, update some fields in `setup.py:setup`.
Version `setuptools_scm` for Python 2.7 and Python 3. #110

setup.py add/update classifier fields

---

pike/__init__.py

Tagging pike 0.2x as 0.2.27 since the need is to make a Kerberos build available for pike based on Python 2 for repos which still use that.
Testing Done
[Test_Results.txt](https://github.com/emc-isilon/pike/files/7332236/Test_Results.txt)

pike 0.2.27

---

.github/workflows/test_samba.yml
pike/auth.py
pike/test/internal/test_auth.py

Avoid multiple splits when the data contains the delimiter.
Fixes #116

pike.auth: maxsplit=1 for password and domain

---

pike/model.py
pike/smb2.py

(Related to new tests for PSCALE-128466)

Add support for V2 SMB leases so that epoch checking can be done.

---

.github/workflows/test_samba.yml

avoid `python setup.py` which can't handle extended metadata preventing incompatible packages from being downloaded

test_samba.yml: pip install pike

---

pike/crypto.py
pike/digest.py
pike/ntlm.py
setup.py

While `pycryptodomex` and `pycryptodome` have similar lineages,
`pycryptodomex` doesn't seem to be as actively developed as
`pycryptodome` is.
Keep the `cryptodomex` namespace imports in place to allow existing
users to use `cryptodomex`, if it's already installed.
Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>

Use `pycryptodome` instead of `pycryptodomex`

---

README.md
pykerb/vendor/py3c.h
pykerb/vendor/py3c/capsulethunk.h
pykerb/vendor/py3c/comparison.h
pykerb/vendor/py3c/compat.h
pykerb/vendor/py3c/fileshim.h
pykerb/vendor/py3c/py3shims.h
pykerb/vendor/py3c/tpflags.h
setup.py

On i686 centos platforms, alpine linux, macos, and others, py3c may not be easily available in the software repos, so avoid having yet another platform dependency to build, especially for a small header-only library with a compatible license.
This can be removed when py2 support is dropped before 1.0 release

Vendor py3c

---

src/pike/test/persistent.py

---Increased timeout so that test is more resilient to slowness in virtual environment.
Tested locally on CA share
```
PIKE_SERVER=<ip> PIKE_SHARE=<sharename> PIKE_CREDS=<creds> python2 -m unittest pike.test.persistent
........
----------------------------------------------------------------------
Ran 8 tests in 141.545s
OK
```
@sudosantanu @marchhare09

Updated test_resiliency_reconnect_before_timeout

---

localsetup.py

This part will help in releasing the package. 
NOTE: localsetup.py is a copy of setup.py with git tag used for release.
Tested by going to pike folder and running
`python3 ./localsetup.py dist`
...
...
Writing pike-smb2-0.4.5/setup.cfg
Creating tar archive
This will be followed by `twine upload dist/pike-smb2-0.4.5.tar.gz`
CC: @sudosantanu @marchhare09 @siddiw @sgovind

Fix setup.py to release based on git tag
